# Site settings
title: Michael Gilroy
email: michael.gilroy24@gmail.com
url: https://michaeljgilroy.com
enforce_ssl: michaeljgilroy.com
description: "Let's build something cool together. Here, I showcase things you may want to see, such as my resume, social media outlets, and projects that are in the works. I'm an aspiring software engineer, but my expertise is in systems administration and network engineering."
skills: "Software Engineer - Operations Specialist"
meta_author: Gilroy Michael

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 36b5e5 #80B3FF
  primary-rgb: "54,181,229" #"128,179,255"
  secondary: 778899 #FD6E8A
  secondary-dark: 5a6977 #A2122F

# Footer settings
footer:
  copyright: Michael Gilroy
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/michaeljgilroy
  - title: linkedin
    url: http://linkedin.com/in/michaeljgilroy
  - title: quora.com 
    url: http://quora.com/profile/Michael-Gilroy-2
  - title: keybase.io
    url: http://keybase.io/gilroy
  - title: github
    url: http://github.com/gilroy

# Postal address (add as many lines as necessary)
address:
  - line: 730 29th Street Unit 913
  - line: Boulder, CO 80303

# Credits content
credits: 'Website designed by yours truly, with the help of the <a href="http://github.com/jeromelachaud/freelancer-theme">Freelancer Jekyll theme</a> from @jeromelachaud on GitHub.'

# Build settings
markdown: kramdown
permalink: pretty
